name: Lint

on:
  pull_request:
    branches:
      - 'master'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Swift code with SwiftLint
        uses: stanfordbdhg/action-swiftlint@v4
